### ISSUE TITLE
Any way to have it run the tests in the background?

### ISSUE THREAD

**Issue by nbashaw** [desktoppr/wbench#7]
First of all, I really love wbench. Awesome stuff. That being said, is there any way to make it not open and close google chrome in the foreground to run the tests? It would be much nicer if that stuff ran in the background.

Thanks!

**Comment by cassioKenji** [comment]
Hello!
Since version 59 Google Chrome is being shipped with a headless feature and it is easy to run headless with chrome: --headless.

There is an way to pass flags to Chrome with wbench?

Thanks!
